### ISSUE TITLE
No valid auth error when no authentication is set up

### ISSUE THREAD

**Issue by lutzee** [therealbill/redskull#27]
Hi, I'm currently setting up Redskull to work with our current Redis/sentinel environment.
Currently we have 4 sentinel servers, Redskull is installed on one of these and will pick up the Redis/sentinel environment from the sentinel instance running on this server. The Redis servers and sentinels are not set up with any of the Redis authentication and can be freely connected to, these servers sit inside a secure network away from access from the outside world.

From the server output I can see the following set of messages when loading the dashboard in Redskull

    2015/07/09 16:10:58.299395 Dashboard requested %v2015-07-09 16:10:58.299375861 +0100 BST
    2015/07/09 16:10:58.299409 Dashboard context set up 27.858µs from dash call
    2015/07/09 16:10:58.299413 dashboard calling GetPodsInError
    2015/07/09 16:10:58.299418 GetPodsInError called
    2015/07/09 16:10:58.299422 ErrorPodCount called
    2015/07/09 16:10:58.299425 ErrorPodCount calling full check
    2015/07/09 16:10:58.302166 redis-session-master has no valid auth, so considered unable to failover
    2015/07/09 16:10:58.302180 pod redis-session-master has errors
    2015/07/09 16:10:58.304285 redis-dev-master has no valid auth, so considered unable to failover
    2015/07/09 16:10:58.304294 pod redis-dev-master has errors
    2015/07/09 16:10:58.305881 redis-only-master has no valid auth, so considered unable to failover
    2015/07/09 16:10:58.305890 pod redis-only-master has errors
    2015/07/09 16:10:58.308397 redis-master has no valid auth, so considered unable to failover
    2015/07/09 16:10:58.308406 pod redis-master has errors
    2015/07/09 16:10:58.310548 redis-test-master has no valid auth, so considered unable to failover
    2015/07/09 16:10:58.310557 pod redis-test-master has errors
    2015/07/09 16:10:58.317071 redis-output-master has no valid auth, so considered unable to failover
    2015/07/09 16:10:58.317080 pod redis-output-master has errors
    2015/07/09 16:10:58.317088 Dashboard error pod call 17.709701ms from dash call
    2015/07/09 16:10:58.317093 redis-session-master has no valid auth, so considered unable to failover
    2015/07/09 16:10:58.317096 redis-dev-master has no valid auth, so considered unable to failover
    2015/07/09 16:10:58.317100 redis-only-master has no valid auth, so considered unable to failover
    2015/07/09 16:10:58.317103 redis-master has no valid auth, so considered unable to failover
    2015/07/09 16:10:58.317106 redis-test-master has no valid auth, so considered unable to failover
    2015/07/09 16:10:58.317109 redis-output-master has no valid auth, so considered unable to failover
    2015/07/09 16:10:58.317117 NoAuth: 0
    2015/07/09 16:10:58.317122 Dashboard iterated over pods in error in  17.74413ms from dash call
    2015/07/09 16:10:58.319443 ErrorPodCount called
    2015/07/09 16:10:58.319458 short interval, not refreshing data
    2015/07/09 16:10:58.319822 redis-session-master has no valid auth, so considered unable to failover
    2015/07/09 16:10:58.319843 redis-dev-master has no valid auth, so considered unable to failover
    2015/07/09 16:10:58.319860 redis-only-master has no valid auth, so considered unable to failover
    2015/07/09 16:10:58.319877 redis-master has no valid auth, so considered unable to failover
    2015/07/09 16:10:58.319896 redis-test-master has no valid auth, so considered unable to failover
    2015/07/09 16:10:58.319921 redis-output-master has no valid auth, so considered unable to failover
    2015/07/09 16:10:58.319947 Dashboard completed  20.569406ms from dash call

Why am i seeing these errors? Authentication isn't set up, failover works fine

**Comment by therealbill** [comment]
Authentication in Redis instances is currently required.

**Comment by therealbill** [comment]
It is possible for this to change when Consul integration is implemented, but not currently expected.

**Comment by lutzee** [comment]
Our issue for this at the moment is that our environment is currently serving caching on a large traffic heavy website, it's not going to be easy for us to make the change to enable authentication without some form of downtime and loss of revenue. We will investigate our options on planning the move to enable authentication, hopefully we can find a way to do it with minimal disruption.

By the way, I'm not sure what you mean by consul, can you point me in the right direction for some information?

**Comment by therealbill** [comment]
Consul is cluster orchestration tool which I'll be integrating Red Skull with to make RS more cluster aware with regards to itself. The issue is #16 and you can learn more about consul at http://consul.io

Since in your case you are on a trusted network, when implementing authentication you could consider having your clients pull the authentication token (password) from Redskull via the API rather than hard coding it. In such a method I would have the client code retrieve the current password on connect and any time it gets an authentication failure message from Redis. 
Going that route would mean you can leave passwords blank and roll out the code, then enable the password and the clients should pull auth and authenticate w/o any additional restarts. This also means you can roll credentials without a restart as well.

Alternatively you can store the password in config file and as above but reading from the file instead. In this fashion you can use auth only when getting an authentication error. Of course, testing it all out in a staging environment would be highly recommended. ;)

**Comment by lutzee** [comment]
Our clients (the websites) uses the stackexchange.redis library, so I'm not sure what you are suggesting would be possible unfortunately. Of course we do have internal testing environments to use before making changes to the live environment :)

**Comment by therealbill** [comment]
Ah, for that client I'd explore catching the `ConnectionFailed` event and checking the `ErrorMessage` to see if it was an auth error. Then you should be able to detect a failed auth, pull the password, and then set it according to https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Configuration.md

Since that would all be done outside of the library in your connection error handling code, it seems possible - indeed perhaps easier than in most client libraries. That said, I don't use that library, so I could be mistaken. 

Also note that yes, sentinel can still manage the failover and will detect topology additions, but you may not be able to make those changes from within Redskull.

**Comment by therealbill** [comment]
Also, I haven't really talked about it publicly yet (it's an experiment) but I am running a Slack channel for Redskull discussion, if you want to try it out shoot me your email address to therealbill@me.com and I'll send you an invite.

**Comment by lutzee** [comment]
We have the library set up in such a way that the website holds the connections open to the servers, if the connection is lost for whatever reason the library will continuously retry to get the connection. I'll take the assumption that when this re connection occurs it should resend the AUTH command after reconnecting using the password set up in the stackexchange.redis config/connection string. 

As for slack, I don't use it, only use IRC really.

**Comment by therealbill** [comment]
Holding the connection is the right way to go. I would make the same assumption that the library would send the "new" password as well. You could set the new password in the config, then send the AUTH command yourself to allow open connections to be able to continue w/o needing to reconnect. That is probably how I'd do it.

**Comment by therealbill** [comment]
Given the strong recommendation for requiring authentication I'm not going to be changing this requirement.
